# Generated by Django 5.0.4 on 2025-04-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
    ]
