# Generated by Django 5.0.4 on 2025-04-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='actic',
            new_name='active',
        ),
    ]
